export const gridButtonsData = [
  { label: 'Impressionist', imageUrl: '/images/impressionism.jpg', id: 'impressionist' },
  { label: 'Art Deco', imageUrl: '/images/art-deco.avif', id: 'art-deco' },
  { label: 'Abstract Expressionist', imageUrl: '/images/abstract-expressionism.jpeg', id: 'abstract-expressionist' },
  { label: 'Fauvist', imageUrl: '/images/fauvism.jpeg', id: 'fauvist' },
  { label: 'Romantic', imageUrl: '/images/romanticism.jpg', id: 'romantic' },
  { label: 'Futurist', imageUrl: '/images/futurism.jpg', id: 'futurist' },
  { label: 'Rococo', imageUrl: '/images/rococo.jpg', id: 'rococo' },
  { label: 'Classical', imageUrl: '/images/classicism.jpg', id: 'classical' },
  { label: 'Cubist', imageUrl: '/images/cubism.jpg', id: 'cubist' },
  { label: 'Pop Art', imageUrl: '/images/pop-art.jpg', id: 'pop-art' },
  { label: 'Realist', imageUrl: '/images/realism.jpg', id: 'realist' },
  { label: 'Conceptual', imageUrl: '/images/conceptual-art.jpg', id: 'conceptual' },
  { label: 'Dada', imageUrl: '/images/dadaism.jpg', id: 'dada' },
  { label: 'Contemporary', imageUrl: '/images/contemporary-art.webp', id: 'contemporary' },
  { label: 'Abstract', imageUrl: '/images/abstract-art.webp', id: 'abstract' },
  { label: 'Expressionist', imageUrl: '/images/expressionism.webp', id: 'expressionist' },
  { label: 'Surrealist', imageUrl: '/images/surrealism.jpg', id: 'surrealist' },
  { label: 'Art Nouveau', imageUrl: '/images/art-nouveau.webp', id: 'art-nouveau' },
  { label: 'Renaissance', imageUrl: '/images/renaissance.jpg', id: 'renaissance' },
  { label: 'Constructivist', imageUrl: '/images/constructivism.JPG', id: 'constructivist' },
  { label: 'Neoclassical', imageUrl: '/images/neoclassicism.webp', id: 'neoclassical' },
  { label: 'Bauhaus', imageUrl: '/images/bauhaus.jpg', id: 'bauhaus' },
  { label: 'Minimalist', imageUrl: '/images/minimalism.webp', id: 'minimalist' },
  { label: 'Baroque', imageUrl: '/images/baroque.jpg', id: 'baroque' },
  { label: 'Pointillist', imageUrl: '/images/pointillism.jpg', id: 'pointillist' },
  { label: 'Pencil Drawing', imageUrl: '/images/pencil.jpeg', id: 'pencil-drawing' },
  { label: 'Graffiti', imageUrl: '/images/graffiti.jpeg', id: 'graffiti' },
  { label: 'Symbolist', imageUrl: '/images/symbolism.jpg', id: 'symbolist' }
];