export const gridButtonsData = [
    { label: 'Impressionism', imageUrl: '/images/impressionism.jpg', id: 'impressionism' },
    { label: 'Abstract Expressionism', imageUrl: '/images/abstract-expressionism.jpeg', id: 'abstract-expressionism' },
    { label: 'Art Deco', imageUrl: '/images/art-deco.avif', id: 'art-deco' },
    { label: 'Fauvism', imageUrl: '/images/fauvism.jpeg', id: 'fauvism' },
    { label: 'Romanticism', imageUrl: '/images/romanticism.jpg', id: 'romanticism' },
    { label: 'Futurism', imageUrl: '/images/futurism.jpg', id: 'futurism' },
    { label: 'Rococo', imageUrl: '/images/rococo.jpg', id: 'rococo' },
    { label: 'Classicism', imageUrl: '/images/classicism.jpg', id: 'classicism' },
    { label: 'Cubism', imageUrl: '/images/cubism.jpg', id: 'cubism' },
    { label: 'Pop art', imageUrl: '/images/pop-art.jpg', id: 'pop-art' },
    { label: 'Realism', imageUrl: '/images/realism.jpg', id: 'realism' },
    { label: 'Conceptual art', imageUrl: '/images/conceptual-art.jpg', id: 'conceptual-art' },
    { label: 'Dadaism', imageUrl: '/images/dadaism.jpg', id: 'dadaism' },
    { label: 'Abstract art', imageUrl: '/images/abstract-art.webp', id: 'abstract-art' },
    { label: 'Contemporary art', imageUrl: '/images/contemporary-art.webp', id: 'contemporary-art' },
    { label: 'Expressionism', imageUrl: '/images/expressionism.webp', id: 'expressionism' },
    { label: 'Surrealsim', imageUrl: '/images/surrealism.jpg', id: 'surrealism' },
    { label: 'Art Nouveau', imageUrl: '/images/art-nouveau.webp', id: 'art-nouveau' },
    { label: 'Renaissance', imageUrl: '/images/renaissance.jpg', id: 'renaissance' },
    { label: 'Constructivism', imageUrl: '/images/constructivism.JPG', id: 'constructivism' },
    { label: 'Neoclassicism', imageUrl: '/images/neoclassicism.webp', id: 'neoclassism' },
    { label: 'Bauhaus', imageUrl: '/images/bauhaus.jpg', id: 'bauhaus' },
    { label: 'Minimalism', imageUrl: '/images/minimalism.webp', id: 'minimalism' },
    { label: 'Baroque', imageUrl: '/images/baroque.jpg', id: 'baroque' }
  ];